### ISSUE TITLE
H5 libraries need to be recompiled with the new toolchain.

### ISSUE THREAD

**Issue by jimhester** [mannau/h5-libwin#1]
The next version of R (3.3.0) is going to be using a new toolchain based on gcc 4.9.3. Because of this system libraries (such as HDF5) need to be recompiled. More information about the toolchain can be found at (https://github.com/rwinlib/r-base)

Do you have documentation on what configure/cmake options you used for the current hdf5 binaries (and version of hdf5 used) or can you provide updated binaries built with the new toolchain?

If you do the latter you will need to test using [R-3.3.0 beta](https://cran.r-project.org/bin/windows/base/R-3.3.0beta-win.exe) and [Rtools33](https://cran.r-project.org/bin/windows/Rtools/Rtools33.exe). The new toolchain is actually two separate toolchains (for 32 and 64bit) rather than a multilib toolchain as previously so you will have to modify your PATH to point to the proper toolchain when compiling for each architecture.

If you provide the necessary options I can do the builds on my machine, but running a naive `./configure ---enable-cxx && make` is failing during compilation.

**Comment by mannau** [comment]
thanks for pointing it out - didn't have time to look into the new toolchain yet.
Check https://github.com/mannau/h5/blob/master/INSTALL 3.1 for the steps I followed.
best,
m
